#!/bin/python3.10
# Author: Salvatore Santoro <sal.santoro@studenti.unina.it>
# Author: Vincenzo Maisto <vincenzo.maisto2@unina.it>
# Description: Parse PBUS config and generate HAL header

import sys
import os

# Check for correct number of arguments
if len(sys.argv) != 3:
    print("Usage: '<CONFIG_PERIPHERALS_CSV>' <OUTPUT_HAL_CONF_FILE>")
    sys.exit(1)

peripheral_csv_path = sys.argv[1]
output_hal_conf_file = sys.argv[2]

if peripheral_csv_path is None:
    print("[ERROR]: config_peripheral_bus.csv not found")
    sys.exit(1)

# List of device peripherals
devices = list()

# Open the file whose path is stored in peripheral_csv_path
with open(peripheral_csv_path, 'r') as file:
    # For each line
    for line in file:
        # Parse RANGE_NAMES
        if line.startswith('RANGE_NAMES'):
            # Split line by comma, then take the right-hand side (after first comma)
            names_str = line.strip().split(',', 1)[1]
            names = names_str.split()
            # For each peripheral
            for name in names:
                # Timers (assume prefix)
                if name.startswith('TIM'):
                    # Append generic device name to enable bare-metal driver
                    devices.append('TIM')
                # Generic
                else:
                    devices.append(name)
            break  # No need to process further lines

# Extract base name and make it a valid macro name for the include guard
base_filename = os.path.basename(output_hal_conf_file).replace('.', '_').upper()
include_guard = f"__{base_filename}__"

# Prepare the lines to write
lines = [
    "// THIS FILE IS AUTOGENERATED, DON'T TOUCH!",
    f"#ifndef {include_guard}",
    f"#define {include_guard}",
    "",
]

# For each device
for device in devices:
    macro_name = f"{device.upper()}_IS_ENABLED"
    lines.append(f"#define {macro_name} 1")

lines.append("")
lines.append(f"#endif // {include_guard}")

# Write to file (overwriting if it exists)
with open(output_hal_conf_file, 'w') as f:
    f.write("\n".join(lines))
