# Author: Vincenzo Maisto <vincenzo.maisto2@unina.it>
# Description: Mark nets in the post-syntesis netlist for debug

# System master AXI interface
# set_property MARK_DEBUG 1 [get_nets HLS_CONTROL_axilite_araddr*  ]
set_property MARK_DEBUG 1 [get_nets HLS_CONTROL_axilite_arvalid* ]
# set_property MARK_DEBUG 1 [get_nets HLS_CONTROL_axilite_rdata*   ]
set_property MARK_DEBUG 1 [get_nets HLS_CONTROL_axilite_rvalid*  ]
# set_property MARK_DEBUG 1 [get_nets HLS_CONTROL_axilite_awaddr*  ]
set_property MARK_DEBUG 1 [get_nets HLS_CONTROL_axilite_awvalid*  ]
# set_property MARK_DEBUG 1 [get_nets HLS_CONTROL_axilite_wdata*   ]
set_property MARK_DEBUG 1 [get_nets HLS_CONTROL_axilite_wvalid*  ]
set_property MARK_DEBUG 1 [get_nets HLS_CONTROL_axilite_bvalid*  ]
# Whole master
# set_property MARK_DEBUG 1 [get_nets MBUS_masters_axi_awid[4]*     ]
set_property MARK_DEBUG 1 [get_nets MBUS_masters_axi_awaddr[4]*   ]
set_property MARK_DEBUG 1 [get_nets MBUS_masters_axi_awlen[4]*    ]
set_property MARK_DEBUG 1 [get_nets MBUS_masters_axi_awsize[4]*   ]
set_property MARK_DEBUG 1 [get_nets MBUS_masters_axi_awburst[4]*  ]
# # set_property MARK_DEBUG 1 [get_nets MBUS_masters_axi_awlock[4]*   ]
# # set_property MARK_DEBUG 1 [get_nets MBUS_masters_axi_awcache[4]*  ]
# # set_property MARK_DEBUG 1 [get_nets MBUS_masters_axi_awprot[4]*   ]
# # set_property MARK_DEBUG 1 [get_nets MBUS_masters_axi_awqos[4]*    ]
set_property MARK_DEBUG 1 [get_nets MBUS_masters_axi_awvalid[4]*  ]
set_property MARK_DEBUG 1 [get_nets MBUS_masters_axi_awready[4]*  ]
# # set_property MARK_DEBUG 1 [get_nets MBUS_masters_axi_awregion[4]* ]
set_property MARK_DEBUG 1 [get_nets MBUS_masters_axi_wdata[4]*    ]
set_property MARK_DEBUG 1 [get_nets MBUS_masters_axi_wstrb[4]*    ]
set_property MARK_DEBUG 1 [get_nets MBUS_masters_axi_wlast[4]*    ]
set_property MARK_DEBUG 1 [get_nets MBUS_masters_axi_wvalid[4]*   ]
# set_property MARK_DEBUG 1 [get_nets MBUS_masters_axi_wready[4]*   ]
# set_property MARK_DEBUG 1 [get_nets MBUS_masters_axi_bid[4]*      ]
set_property MARK_DEBUG 1 [get_nets MBUS_masters_axi_bresp[4]*    ]
set_property MARK_DEBUG 1 [get_nets MBUS_masters_axi_bvalid[4]*   ]
# set_property MARK_DEBUG 1 [get_nets MBUS_masters_axi_bready[4]*   ]
set_property MARK_DEBUG 1 [get_nets MBUS_masters_axi_araddr[4]*   ]
set_property MARK_DEBUG 1 [get_nets MBUS_masters_axi_arlen[4]*    ]
set_property MARK_DEBUG 1 [get_nets MBUS_masters_axi_arsize[4]*   ]
set_property MARK_DEBUG 1 [get_nets MBUS_masters_axi_arburst[4]*  ]
# set_property MARK_DEBUG 1 [get_nets MBUS_masters_axi_arlock[4]*   ]
# set_property MARK_DEBUG 1 [get_nets MBUS_masters_axi_arcache[4]*  ]
# set_property MARK_DEBUG 1 [get_nets MBUS_masters_axi_arprot[4]*   ]
# set_property MARK_DEBUG 1 [get_nets MBUS_masters_axi_arqos[4]*    ]
set_property MARK_DEBUG 1 [get_nets MBUS_masters_axi_arvalid[4]*  ]
set_property MARK_DEBUG 1 [get_nets MBUS_masters_axi_arready[4]*  ]
# set_property MARK_DEBUG 1 [get_nets MBUS_masters_axi_arid[4]*     ]
# set_property MARK_DEBUG 1 [get_nets MBUS_masters_axi_arregion[4]* ]
# set_property MARK_DEBUG 1 [get_nets MBUS_masters_axi_rid[4]*      ]
set_property MARK_DEBUG 1 [get_nets MBUS_masters_axi_rdata[4]*    ]
set_property MARK_DEBUG 1 [get_nets MBUS_masters_axi_rresp[4]*    ]
set_property MARK_DEBUG 1 [get_nets MBUS_masters_axi_rlast[4]*    ]
set_property MARK_DEBUG 1 [get_nets MBUS_masters_axi_rvalid[4]*   ]
set_property MARK_DEBUG 1 [get_nets MBUS_masters_axi_rready[4]*   ]