#ifndef UNINASOC_H
#define UNINASOC_H

// This header is autogenerated based on project configuration
#include "uninasoc_conf.h"
#include "stlib.h"

#include "plic.h"
#include "irq_handlers.h"

#ifdef GPIO_IN_IS_ENABLED 
#include "xlnx_gpio_in.h"
#endif

#ifdef GPIO_OUT_IS_ENABLED
#include "xlnx_gpio_out.h"
#endif

#ifdef TIM_IS_ENABLED
#include "xlnx_tim.h"
#endif

void uninasoc_init(void);

#endif
